version: '2'
services:
    coco-app:
        image: coco
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://coco-mysql:3306/coco?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=coco-elasticsearch:9300
        ports:
            - 8080:8080
    coco-mysql:
        extends:
            file: mysql.yml
            service: coco-mysql
    coco-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: coco-elasticsearch
